---
title: "Lee Carter and the implemntation were using"
format:
  pdf:
    fig-width: 8
    fig-height: 4
bibliography: references.bib
---

# Lee Carter

The Lee-carter model was introduced in 1992 by Ronald Lee and Lawrence Carter in their paper "Modeling and Forecasting U.S. Mortality". It revolutionized mortality forecasting by providing a data-driven approach in lieu of the expert-led methods that were previously dominant. Prior to its development, official forcasts often underestimated the gains in human life expectancy, creating a pressing need for more accurate projections to asses the solvency of pension systems and social security programs.

The models core innovation was its ability to reduce the matrix of log age specific death rates into a single time varying mortality index {K_t} an age specific sensitivity parameter {b_x}. and a baseline mortality rate {a_x}. To achieve this, Lee and Carter applied Singular Value Decomposition (SVD) to extract the characteristic pattern of mortality improvement over time. Unfortunately, the solution to the SVD is not unique, so they imposed two constraints: the sum of {b_x} across ages must equal 1, and the sum of {K_t} across time must equal 0. This allowed them to identify a unique solution that captured the dominant trend in mortality improvement. Then by only taking the first singular value and its corresponding vectors in {a_x} and {b_x}, they reduce the complexity of the data while retaining the most important information. This serves as compression of the data reducing the number of parameters needed to model mortality trends but keeping the essential features of the data. Following this, the time-varying mortality index {K_t} is modeled as a random walk with drift, allowing for the creation of objective prediction intervals that provided a quantifiable measure of uncertainty. This was a significant departure from previous "best-guess" forecasts, which lacked any formal way to assess the range of possible outcomes.

The simplicity and robustness of the Lee-Carter model allowed it to outperform contemporary models in backtesting, closely tracking actual mortality data while older models significantly under-predicted life expectancy gains. Its ability to capture the linear trend of log-mortality decline across the 20th century made it particularly effective for long-term forecasting. Unlike earlier parametric models that focused on the biological shape of the mortality curve at a single point in time, the Lee-Carter model prioritized the dynamic movement of that curve over decades.

Thanks to the nature of the Lee-Carter model extensions and variations have been developed to address its limitations and improve its accuracy. For example, the LC-ER (Extended Rotation) method was developed to account for "rotation" in mortality decline, which addresses implausible age-pattern artifacts in vanilla LC projections. Additionally, the stmomo R package, whose implementation we will be using later, provides a flexible framework for mortality forecasting using the Lee-Carter model as well as several other models, allowing users to fit the model to various data types and generate forecasts while assessing uncertainty.

The model and its extensions have been used in various applications, including forecasting breast cancer mortality in China and Pakistan, where it outperformed simpler models for the screen-age/late-onset population (ages 50–84), revealing rising mortality in Pakistan versus declining rates in China, which was used to inform targeted healthcare interventions. The UN employs the LC model to forecast global mortality trends, especially for long-term projections up to 2100. For high-life-expectancy countries like Japan, the model was extended to account for “rotation” in mortality decline (slowing improvements at young ages and accelerating declines at older ages). This adjustment, termed the LC-ER (Extended Rotation) method, addressed implausible age-pattern artifacts in vanilla LC projections [@booth_baselini_carmada_2023]

Now, when talking about the implementation we will be using, Stochastic Mortality Modeling (stMoMo) is an R package that provides a comprehensive framework for fitting and forecasting mortality models, including the Lee-Carter model. The stMoMo package allows users to easily fit the Lee-Carter model to their mortality data, generate forecasts, and assess uncertainty through confidence intervals. It also includes various extensions of the Lee-Carter model, such as the LC-ER method, which can be used to improve the accuracy of forecasts for high-life-expectancy countries. The package is designed to be user-friendly and flexible, making it accessible for researchers and practitioners in the field of mortality forecasting. For out usecase, we will be using the base Lee-Carter model and using its initial fit to bootstrap its parameters to then simulate numerous forecasts to create a distribution of possible outcomes. For this we need to set several parameter. First would be the link function, which determines the random component associated with the mortality model. The default link function is the log link, this assumes that the deaths follow a Poisson distribution, which is appropriate for count data like mortality. Secondly, we need to set the restraints for the model to ensure identifiability. For this we will set it as "sum". This ensures that $\Sigma_t k_t=0$. With these two we can now create the seed fit for the bootstrapping proccess. The bootstrap itself requires its own set of parameters, these being the number of bootstrap samples, the approach to be applied and the type of death to resample. After several cycles, we determined that 100 samples generated properly distributed residuals, but for robustness, we choose 500 since it still fit comfortably with the resources at hand. 



















# References
